In [2]:
import pandas as pd 

df = pd.read_csv('data/raw/fight-songs-updated.csv')

In [3]:
df_big = df[df["conference"] == "Big Ten"]
df_big

,school,conference,song_name,writers,year,student_writer,official_song,contest,bpm,sec_duration,...,win_won,victory_win_won,rah,nonsense,colors,men,opponents,spelling,trope_count,spotify_id
24,Illinois,Big Ten,Oskee-Wow-Wow,H.R. Green and H.V. Hill,1910,Yes,Yes,No,162,60,...,No,Yes,Yes,Yes,Yes,Yes,Yes,No,6,6C0vaoMxzM21yYgJBmGx5K
25,Indiana,Big Ten,"Indiana, Our Indiana",Russell P. Harker and Karl L. King,1912,Yes,Yes,No,150,63,...,No,No,No,No,Yes,No,No,Yes,3,2Wbo5zdRDnq4pOgWL9avaG
26,Iowa,Big Ten,Iowa Fight Song,Meredith Willson,1950,No,Yes,No,150,72,...,Yes,Yes,Yes,No,No,No,No,No,3,604ELPPFgbFlW0SHoEYVJw
27,Maryland,Big Ten,Maryland Fight Song,Ralph Davis,1939,Yes,Yes,No,142,56,...,Yes,Yes,No,No,No,No,No,No,3,6PKoPWKJLOBI2K33RkFvbc
28,Michigan,Big Ten,The Victors,Louis Elbel,1898,Yes,Yes,No,83,122,...,No,No,No,No,No,No,No,No,0,6wVbHLCBOCqp6052WcWXLG
29,Michigan State,Big Ten,Victory for MSU,Francis Irving Lankey and Arthur L. Sayles,1915,Yes,Yes,No,145,112,...,Yes,Yes,Yes,No,Yes,No,No,Yes,5,4BSrPApxbeUNPA5Q8LyfMd
30,Minnesota,Big Ten,The Minnesota Rouser,Floyd Hutsell,1909,No,Yes,Yes,151,60,...,No,No,Yes,Yes,No,No,No,Yes,3,2EeyLSmHKdZulOKGcTpLS0
31,Nebraska,Big Ten,Dear Old Nebraska U.,Harry Pecha,1924,Yes,No,No,136,94,...,No,No,No,No,No,Yes,No,No,1,7z2TihIyf3IZR1r0AmI1Ik
32,Northwestern,Big Ten,Go! U Northwestern,Theodore C. Van Etten,1912,Yes,Yes,No,140,57,...,Yes,Yes,Yes,No,No,No,No,No,4,4iWO9U49SZ0vvzto7qxRxN
33,Ohio State,Big Ten,Buckeye Battle Cry,Frank Crumit,1919,No,Yes,Yes,178,89,...,Yes,Yes,No,No,Yes,Yes,No,No,5,2faIedehtxwQqYxRRc6T2L
34,Penn State,Big Ten,"Fight On, State",Joseph Sanders,1933,No,Yes,No,145,81,...,Yes,Yes,No,No,Yes,No,No,Yes,5,5InlNNfIFQAvCL78VFgR5O
35,Purdue,Big Ten,Hail Purdue,James R. Morrison and Edward S. Wotawa,1912,Yes,Yes,No,160,86,...,No,Yes,No,No,Yes,No,No,No,2,1bYZgec19T5gQJAUeIzq9W
36,Rutgers,Big Ten,The Bells Must Ring,Richard Hadden and W.E. Sanford,1931,Yes,Yes,Yes,75,74,...,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,8,7EdGMXzZjJKNHJaszbWTHi
37,Wisconsin,Big Ten,"On, Wisconsin",William Purdy and Carl Beck,1909,No,Yes,No,132,134,...,Yes,Yes,No,No,No,Yes,No,No,3,4DmMOLdp4ZYvrAqemDBBbJ
38,Oregon,Big Ten,Mighty Oregon,DeWitt Gilbert and Albert John Perfect,1916,Yes,Yes,No,65,80,...,Yes,Yes,No,No,No,Yes,Yes,No,5,4zPgdoDF3Od2dwQdPlGJtt
39,UCLA,Big Ten,Sons of Westwood,Harold P. Williams and N. Loyall McLaren; Kel...,1959,No,Yes,No,72,69,...,No,No,No,No,Yes,Yes,Yes,Yes,5,0XxQcPAThn9dOZ6NVFUfGl
40,USC,Big Ten,"Fight On, USC",Milo Sweet,1922,Yes,Yes,Yes,75,60,...,Yes,Yes,No,No,No,Yes,No,Yes,5,23EM48kuqZWVltXE9bApcK
41,Washington,Big Ten,Bow Down to Washington,Lester J. Wilson,1915,No,Yes,Yes,139,89,...,No,Yes,Yes,No,Yes,No,No,No,4,0OLQPcJ1jMwrXJbt81hHrx

In [4]:
round(df_big['bpm'].mean(), 2)

np.float64(127.78)

In [5]:
df_big['spelling'].nunique

<bound method IndexOpsMixin.nunique of 24     No
25    Yes
26     No
27     No
28     No
29    Yes
30    Yes
31     No
32     No
33     No
34    Yes
35     No
36    Yes
37     No
38     No
39    Yes
40    Yes
41     No
Name: spelling, dtype: object>

In [6]:
df_big['spelling'] = df_big['spelling'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['opponents'] = df_big['opponents'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['men'] = df_big['men'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['colors'] = df_big['colors'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['nonsense'] = df_big['nonsense'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['rah'] = df_big['rah'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['win_won'] = df_big['win_won'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['victory'] = df_big['victory'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['fight'] = df_big['fight'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['victory_win_won'] = df_big['victory_win_won'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['contest'] = df_big['contest'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['official_song'] = df_big['official_song'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['student_writer'] = df_big['student_writer'].map({'Yes': 1, 'No': 0}).astype(int)
df_big['year'] = df_big['year'].astype(int)

C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['spelling'] = df_big['spelling'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['opponents'] = df_big['opponents'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['men'] = df_big['men'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['colors'] = df_big['colors'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['nonsense'] = df_big['nonsense'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['rah'] = df_big['rah'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['win_won'] = df_big['win_won'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['victory'] = df_big['victory'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['fight'] = df_big['fight'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['victory_win_won'] = df_big['victory_win_won'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['contest'] = df_big['contest'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['official_song'] = df_big['official_song'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['student_writer'] = df_big['student_writer'].map({'Yes': 1, 'No': 0}).astype(int)
C:\Users\12248\AppData\Local\Temp\ipykernel_14908\444879105.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_big['year'] = df_big['year'].astype(int)

In [7]:
df_big["school"].nunique

<bound method IndexOpsMixin.nunique of 24          Illinois
25           Indiana
26              Iowa
27          Maryland
28          Michigan
29    Michigan State
30         Minnesota
31          Nebraska
32      Northwestern
33        Ohio State
34        Penn State
35            Purdue
36           Rutgers
37         Wisconsin
38            Oregon
39              UCLA
40               USC
41        Washington
Name: school, dtype: object>

In [8]:
df_big

,school,conference,song_name,writers,year,student_writer,official_song,contest,bpm,sec_duration,...,win_won,victory_win_won,rah,nonsense,colors,men,opponents,spelling,trope_count,spotify_id
24,Illinois,Big Ten,Oskee-Wow-Wow,H.R. Green and H.V. Hill,1910,1,1,0,162,60,...,0,1,1,1,1,1,1,0,6,6C0vaoMxzM21yYgJBmGx5K
25,Indiana,Big Ten,"Indiana, Our Indiana",Russell P. Harker and Karl L. King,1912,1,1,0,150,63,...,0,0,0,0,1,0,0,1,3,2Wbo5zdRDnq4pOgWL9avaG
26,Iowa,Big Ten,Iowa Fight Song,Meredith Willson,1950,0,1,0,150,72,...,1,1,1,0,0,0,0,0,3,604ELPPFgbFlW0SHoEYVJw
27,Maryland,Big Ten,Maryland Fight Song,Ralph Davis,1939,1,1,0,142,56,...,1,1,0,0,0,0,0,0,3,6PKoPWKJLOBI2K33RkFvbc
28,Michigan,Big Ten,The Victors,Louis Elbel,1898,1,1,0,83,122,...,0,0,0,0,0,0,0,0,0,6wVbHLCBOCqp6052WcWXLG
29,Michigan State,Big Ten,Victory for MSU,Francis Irving Lankey and Arthur L. Sayles,1915,1,1,0,145,112,...,1,1,1,0,1,0,0,1,5,4BSrPApxbeUNPA5Q8LyfMd
30,Minnesota,Big Ten,The Minnesota Rouser,Floyd Hutsell,1909,0,1,1,151,60,...,0,0,1,1,0,0,0,1,3,2EeyLSmHKdZulOKGcTpLS0
31,Nebraska,Big Ten,Dear Old Nebraska U.,Harry Pecha,1924,1,0,0,136,94,...,0,0,0,0,0,1,0,0,1,7z2TihIyf3IZR1r0AmI1Ik
32,Northwestern,Big Ten,Go! U Northwestern,Theodore C. Van Etten,1912,1,1,0,140,57,...,1,1,1,0,0,0,0,0,4,4iWO9U49SZ0vvzto7qxRxN
33,Ohio State,Big Ten,Buckeye Battle Cry,Frank Crumit,1919,0,1,1,178,89,...,1,1,0,0,1,1,0,0,5,2faIedehtxwQqYxRRc6T2L
34,Penn State,Big Ten,"Fight On, State",Joseph Sanders,1933,0,1,0,145,81,...,1,1,0,0,1,0,0,1,5,5InlNNfIFQAvCL78VFgR5O
35,Purdue,Big Ten,Hail Purdue,James R. Morrison and Edward S. Wotawa,1912,1,1,0,160,86,...,0,1,0,0,1,0,0,0,2,1bYZgec19T5gQJAUeIzq9W
36,Rutgers,Big Ten,The Bells Must Ring,Richard Hadden and W.E. Sanford,1931,1,1,1,75,74,...,1,1,1,1,1,1,0,1,8,7EdGMXzZjJKNHJaszbWTHi
37,Wisconsin,Big Ten,"On, Wisconsin",William Purdy and Carl Beck,1909,0,1,0,132,134,...,1,1,0,0,0,1,0,0,3,4DmMOLdp4ZYvrAqemDBBbJ
38,Oregon,Big Ten,Mighty Oregon,DeWitt Gilbert and Albert John Perfect,1916,1,1,0,65,80,...,1,1,0,0,0,1,1,0,5,4zPgdoDF3Od2dwQdPlGJtt
39,UCLA,Big Ten,Sons of Westwood,Harold P. Williams and N. Loyall McLaren; Kel...,1959,0,1,0,72,69,...,0,0,0,0,1,1,1,1,5,0XxQcPAThn9dOZ6NVFUfGl
40,USC,Big Ten,"Fight On, USC",Milo Sweet,1922,1,1,1,75,60,...,1,1,0,0,0,1,0,1,5,23EM48kuqZWVltXE9bApcK
41,Washington,Big Ten,Bow Down to Washington,Lester J. Wilson,1915,0,1,1,139,89,...,0,1,1,0,1,0,0,0,4,0OLQPcJ1jMwrXJbt81hHrx

In [ ]:
df_big.columns

Index(['school', 'conference', 'song_name', 'writers', 'year',
       'student_writer', 'official_song', 'contest', 'bpm', 'sec_duration',
       'fight', 'number_fights', 'victory', 'win_won', 'victory_win_won',
       'rah', 'nonsense', 'colors', 'men', 'opponents', 'spelling',
       'trope_count', 'spotify_id'],
      dtype='object')

: